In [1]:
import numpy as np
import pandas as pd
from copy import deepcopy

In [2]:
def euclidean(a,b, ax=1):
    return np.linalg.norm(a-b, axis=ax)

In [4]:
k = 3
X = pd.read_csv('kmeans.csv',index_col=False)
print(X)


    X1   X2
0  5.9  3.2
1  4.6  2.9
2  6.2  2.8
3  4.7  3.2
4  5.5  4.2
5  5.0  3.0
6  4.9  3.1
7  6.7  3.1
8  5.1  3.8
9  6.0  3.0


In [5]:
x1 = X['X1'].values
x2 = X['X2'].values
X = np.array(list(zip(x1, x2)))
print(X)

[[5.9 3.2]
 [4.6 2.9]
 [6.2 2.8]
 [4.7 3.2]
 [5.5 4.2]
 [5.  3. ]
 [4.9 3.1]
 [6.7 3.1]
 [5.1 3.8]
 [6.  3. ]]


In [8]:
C_x = [6.2, 6.6 ,6.5]
C_y = [3.2, 3.7, 3.0]
Centroid = np.array(list(zip(C_x, C_y)), dtype=np.float32)
print("Initial Centroids")
print(Centroid.shape)

Initial Centroids
(3, 2)


In [9]:
Centroid_old = np.zeros(Centroid.shape)
print(Centroid_old)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [10]:
clusters = np.zeros(len(X))
print(clusters)
error = euclidean(Centroid, Centroid_old, None)
print(error)

[0. 0. 0. 0. 0.]
12.537144692236463


In [13]:
iterr = 0
    # Loop will run till the error becomes zero
while error != 0:
    # Assigning each value to its closest cluster
    iterr = iterr + 1
    for i in range(len(X)):
        #print(X[i])
        distances = euclidean(X[i], Centroid)
        #print(distances)
        cluster = np.argmin(distances)
        clusters[i] = cluster

    Centroid_old = deepcopy(Centroid)
        
    # Finding the new centroids by taking the Mean
    for p in range(k):
        points = [X[j] for j in range(len(X)) if clusters[j] == p]
        Centroid[p] = np.mean(points, axis=0)
    print(" Centre of the clusters after ", iterr," Iteration \n", Centroid)
    error = euclidean(Centroid, Centroid_old, None)
    print("Error  ... ",error)  

/home/root1/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3118: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/root1/anaconda3/lib/python3.7/site-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


 Centre of the clusters after  1  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11  Iter

 Centre of the clusters after  230  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  231  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  232  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  233  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  234  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  235  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  236  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  237  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  238  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  239  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clust

 Centre of the clusters after  386  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  387  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  388  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  389  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  390  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  391  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  392  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  393  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  394  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  395  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clust

 Centre of the clusters after  560  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  561  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  562  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  563  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  564  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  565  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  566  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  567  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  568  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  569  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clust

Error  ...  nan
 Centre of the clusters after  730  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  731  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  732  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  733  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  734  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  735  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  736  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  737  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  738  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  739  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Cen

Error  ...  nan
 Centre of the clusters after  840  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  841  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  842  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  843  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  844  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  845  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  846  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  847  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  848  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  849  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Cen

 Centre of the clusters after  955  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  956  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  957  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  958  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  959  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  960  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  961  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  962  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  963  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  964  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clust

 Centre of the clusters after  1101  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1102  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1103  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1104  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1105  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1106  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1107  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1108  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1109  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1110  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of

 Centre of the clusters after  1263  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1264  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1265  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1266  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1267  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1268  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1269  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1270  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1271  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1272  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of

 Centre of the clusters after  1464  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1465  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1466  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1467  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1468  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1469  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1470  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1471  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1472  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1473  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of

Error  ...  nan
 Centre of the clusters after  1625  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1626  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1627  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1628  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1629  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1630  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1631  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1632  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1633  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1634  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...

 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1774  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1775  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1776  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1777  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1778  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1779  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1780  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1781  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1782  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1783  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]

 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1931  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1932  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1933  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1934  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1935  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1936  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1937  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1938  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1939  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  1940  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]

Error  ...  nan
 Centre of the clusters after  2079  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2080  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2081  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2082  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2083  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2084  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2085  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2086  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2087  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2088  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...

Error  ...  nan
 Centre of the clusters after  2215  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2216  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2217  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2218  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2219  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2220  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2221  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2222  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2223  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2224  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...

 Centre of the clusters after  2379  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2380  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2381  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2382  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2383  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2384  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2385  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2386  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2387  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2388  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of

Error  ...  nan
 Centre of the clusters after  2512  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2513  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2514  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2515  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2516  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2517  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2518  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2519  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2520  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2521  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...

 Centre of the clusters after  2645  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2646  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2647  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2648  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2649  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2650  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2651  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2652  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2653  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2654  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of

Error  ...  nan
 Centre of the clusters after  2787  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2788  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2789  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2790  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2791  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2792  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2793  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2794  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2795  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2796  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...

 Centre of the clusters after  2927  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2928  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2929  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2930  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2931  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2932  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2933  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2934  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2935  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  2936  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of

Error  ...  nan
 Centre of the clusters after  3147  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3148  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3149  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3150  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3151  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3152  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3153  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3154  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3155  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3156  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...

Error  ...  nan
 Centre of the clusters after  3411  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3412  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3413  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3414  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3415  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3416  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3417  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3418  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3419  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3420  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...

 Centre of the clusters after  3603  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3604  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3605  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3606  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3607  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3608  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3609  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3610  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3611  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3612  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of

 Centre of the clusters after  3784  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3785  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3786  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3787  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3788  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3789  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3790  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3791  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3792  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3793  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of

Error  ...  nan
 Centre of the clusters after  3915  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3916  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3917  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3918  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3919  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3920  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3921  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3922  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3923  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  3924  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...

Error  ...  nan
 Centre of the clusters after  4025  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4026  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4027  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4028  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4029  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4030  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4031  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4032  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4033  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4034  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...

 Centre of the clusters after  4140  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4141  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4142  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4143  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4144  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4145  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4146  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4147  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4148  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4149  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of

 Centre of the clusters after  4258  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4259  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4260  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4261  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4262  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4263  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4264  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4265  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4266  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4267  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of

 Centre of the clusters after  4373  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4374  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4375  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4376  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4377  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4378  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4379  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4380  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4381  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4382  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of

 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4501  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4502  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4503  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4504  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4505  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4506  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4507  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4508  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4509  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4510  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]

 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4691  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4692  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4693  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4694  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4695  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4696  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4697  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4698  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4699  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4700  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]

 Centre of the clusters after  4930  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4931  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4932  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4933  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4934  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4935  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4936  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4937  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4938  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  4939  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of

 Centre of the clusters after  5121  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5122  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5123  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5124  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5125  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5126  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5127  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5128  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5129  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5130  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of

Error  ...  nan
 Centre of the clusters after  5306  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5307  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5308  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5309  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5310  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5311  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5312  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5313  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5314  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5315  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...

Error  ...  nan
 Centre of the clusters after  5493  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5494  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5495  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5496  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5497  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5498  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5499  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5500  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5501  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5502  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...

 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5677  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5678  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5679  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5680  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5681  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5682  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5683  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5684  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5685  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5686  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]

 Centre of the clusters after  5822  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5823  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5824  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5825  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5826  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5827  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5828  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5829  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5830  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5831  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of

 Centre of the clusters after  5993  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5994  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5995  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5996  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5997  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5998  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  5999  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6000  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6001  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6002  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of

 Centre of the clusters after  6172  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6173  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6174  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6175  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6176  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6177  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6178  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6179  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6180  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6181  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of

 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6308  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6309  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6310  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6311  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6312  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6313  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6314  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6315  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6316  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6317  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]

 Centre of the clusters after  6530  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6531  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6532  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6533  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6534  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6535  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6536  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6537  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6538  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6539  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of

Error  ...  nan
 Centre of the clusters after  6757  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6758  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6759  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6760  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6761  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6762  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6763  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6764  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6765  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6766  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...

 Centre of the clusters after  6919  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6920  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6921  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6922  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6923  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6924  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6925  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6926  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6927  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  6928  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of

 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7076  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7077  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7078  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7079  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7080  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7081  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7082  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7083  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7084  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7085  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]

 Centre of the clusters after  7213  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7214  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7215  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7216  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7217  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7218  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7219  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7220  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7221  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7222  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of

 Centre of the clusters after  7330  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7331  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7332  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7333  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7334  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7335  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7336  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7337  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7338  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7339  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of

 Centre of the clusters after  7468  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7469  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7470  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7471  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7472  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7473  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7474  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7475  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7476  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7477  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of

 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7593  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7594  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7595  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7596  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7597  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7598  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7599  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7600  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7601  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7602  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]

 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7729  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7730  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7731  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7732  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7733  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7734  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7735  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7736  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7737  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7738  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]

 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7830  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7831  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7832  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7833  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7834  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7835  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7836  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7837  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7838  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7839  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]

 Centre of the clusters after  7928  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7929  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7930  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7931  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7932  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7933  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7934  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7935  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7936  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  7937  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of

 Centre of the clusters after  8040  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8041  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8042  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8043  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8044  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8045  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8046  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8047  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8048  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8049  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of

 Centre of the clusters after  8198  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8199  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8200  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8201  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8202  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8203  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8204  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8205  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8206  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8207  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of

 Centre of the clusters after  8364  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8365  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8366  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8367  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8368  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8369  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8370  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8371  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8372  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8373  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of

Error  ...  nan
 Centre of the clusters after  8555  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8556  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8557  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8558  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8559  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8560  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8561  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8562  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8563  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8564  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...

 Centre of the clusters after  8744  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8745  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8746  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8747  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8748  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8749  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8750  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8751  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8752  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8753  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of

Error  ...  nan
 Centre of the clusters after  8929  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8930  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8931  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8932  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8933  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8934  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8935  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8936  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8937  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  8938  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...

 Centre of the clusters after  9096  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9097  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9098  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9099  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9100  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9101  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9102  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9103  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9104  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9105  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of

Error  ...  nan
 Centre of the clusters after  9294  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9295  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9296  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9297  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9298  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9299  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9300  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9301  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9302  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9303  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...

 Centre of the clusters after  9491  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9492  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9493  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9494  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9495  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9496  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9497  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9498  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9499  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9500  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of

 Centre of the clusters after  9759  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9760  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9761  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9762  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9763  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9764  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9765  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9766  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9767  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9768  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of

 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9972  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9973  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9974  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9975  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9976  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9977  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9978  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9979  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9980  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  9981  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]

 Centre of the clusters after  10172  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10173  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10174  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10175  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10176  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10177  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10178  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10179  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10180  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10181  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan


 Centre of the clusters after  10369  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10370  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10371  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10372  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10373  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10374  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10375  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10376  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10377  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10378  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan


 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10554  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10555  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10556  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10557  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10558  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10559  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10560  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10561  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10562  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10563  Iteration 
 [[1.4 2.4]
 [nan nan]


 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10757  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10758  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10759  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10760  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10761  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10762  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10763  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10764  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10765  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10766  Iteration 
 [[nan nan]
 [1.4 2.4]


 Centre of the clusters after  10947  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10948  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10949  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10950  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10951  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10952  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10953  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10954  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10955  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  10956  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan


 Centre of the clusters after  11142  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11143  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11144  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11145  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11146  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11147  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11148  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11149  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11150  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11151  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan


 Centre of the clusters after  11345  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11346  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11347  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11348  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11349  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11350  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11351  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11352  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11353  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11354  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan


 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11548  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11549  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11550  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11551  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11552  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11553  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11554  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11555  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11556  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11557  Iteration 
 [[1.4 2.4]
 [nan nan]


 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11789  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11790  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11791  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11792  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11793  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11794  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11795  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11796  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11797  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  11798  Iteration 
 [[nan nan]
 [1.4 2.4]


 Centre of the clusters after  12001  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12002  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12003  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12004  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12005  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12006  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12007  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12008  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12009  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12010  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan


 Centre of the clusters after  12191  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12192  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12193  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12194  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12195  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12196  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12197  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12198  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12199  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12200  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan


 Centre of the clusters after  12363  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12364  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12365  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12366  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12367  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12368  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12369  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12370  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12371  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12372  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan


 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12506  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12507  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12508  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12509  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12510  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12511  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12512  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12513  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12514  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12515  Iteration 
 [[1.4 2.4]
 [nan nan]


 Centre of the clusters after  12692  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12693  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12694  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12695  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12696  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12697  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12698  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12699  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12700  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12701  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan


 Centre of the clusters after  12850  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12851  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12852  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12853  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12854  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12855  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12856  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12857  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12858  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  12859  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan


 Centre of the clusters after  13003  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13004  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13005  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13006  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13007  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13008  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13009  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13010  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13011  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13012  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan


 Centre of the clusters after  13155  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13156  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13157  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13158  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13159  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13160  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13161  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13162  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13163  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13164  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan


 Centre of the clusters after  13335  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13336  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13337  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13338  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13339  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13340  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13341  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13342  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13343  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13344  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan


 Centre of the clusters after  13553  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13554  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13555  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13556  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13557  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13558  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13559  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13560  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13561  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13562  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan


Error  ...  nan
 Centre of the clusters after  13755  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13756  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13757  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13758  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13759  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13760  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13761  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13762  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13763  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13764  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]


 Centre of the clusters after  13913  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13914  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13915  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13916  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13917  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13918  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13919  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13920  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13921  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  13922  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan


Error  ...  nan
 Centre of the clusters after  14096  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  14097  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  14098  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  14099  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  14100  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  14101  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  14102  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  14103  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  14104  Iteration 
 [[nan nan]
 [1.4 2.4]
 [nan nan]]
Error  ...  nan
 Centre of the clusters after  14105  Iteration 
 [[1.4 2.4]
 [nan nan]
 [nan nan]]


KeyboardInterrupt: 

In [15]:
print(clusters)

[0. 0. 0. 0. 0.]
